theme: jekyll-theme-minimal
title: Antonia Chroni
description: Welcome to the digital home of Antonia Chroni - researcher, writer and poet at heart. It's nice to meet you.
logo: https://github.com/AntoniaChroni/antoniachroni.github.io/blob/main/github-272865162_1070778917105134_8842346098360367250_n.jpg?raw=true
