theme: jekyll-theme-minimal
title: Antonia Chroni
description: Welcome to the digital home of Antonia Chroni - researcher, writer and poet at heart.
logo: https://github.com/AntoniaChroni/antoniachroni.github.io/blob/main/github-antoniachroni2018.jpeg?raw=true
